server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.15.136:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.15.136

